apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-branch-protection
spec:
  schedule: "0 * * * *"  # Run every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: github-branch-protection
            image: your-docker-image:tag
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
            - name: GITHUB_ORG_NAME
              value: "your-organization-name"
          restartPolicy: OnFailure