name: Build, Scan, and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Docker tag
      id: dockertag
      run: |
        TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}
        echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$TAG"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: siddharthjoshi
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: siddharthjoshi/github-org-branch-protector:${{ env.DOCKER_TAG }}
        outputs: type=docker,dest=/tmp/image.tar

    - name: Load image
      run: |
        docker load --input /tmp/image.tar
        docker image ls -a

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'siddharthjoshi/github-org-branch-protector:${{ env.DOCKER_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push image to DockerHub
      uses: docker/build-push-action@v2
      if: github.event_name != 'pull_request'
      with:
        context: .
        push: true
        tags: siddharthjoshi/github-org-branch-protector:${{ env.DOCKER_TAG }}